const Q=[["Mundiales","¿Quién tiene más goles en la historia de los Mundiales?",["Messi","Cristiano Ronaldo","Miroslav Klose"],2],["Mundiales","¿Qué selección ganó el Mundial 2022?",["Argentina","Francia","Brasil"],0],["Reglas","¿Cuántos jugadores tiene un equipo al comenzar un partido?",["10","11","12"],1],["Mundiales","¿Qué país ganó el Mundial 2014?",["Alemania","Argentina","España"],0],["Leyendas","¿Quién era conocido como O Rei?",["Pelé","Maradona","Zidane"],0],["Mundiales","¿Qué selección tiene más títulos mundiales?",["Brasil","Alemania","Italia"],0],["Reglas","¿Cuánto dura un partido sin tiempo agregado?",["80","90","100"],1],["Reglas","¿Qué tarjeta significa expulsión?",["Amarilla","Azul","Roja"],2],["Uruguay","¿Cuántos Mundiales ganó Uruguay?",["1","2","3"],1],["Leyendas","¿Quién fue capitán de Argentina en el Mundial 1986?",["Batistuta","Maradona","Zanetti"],1]];
const pub=Q.map((x,i)=>({id:i,q:x[1],options:x[2],category:x[0]}));const R=new Map();
const j=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store",...h}});const b=()=>crypto.getRandomValues(new Uint8Array(32));const hex=a=>[...a].map(x=>x.toString(16).padStart(2,"0")).join("");const enc=a=>btoa(String.fromCharCode(...a)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");const hash=async s=>hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s))));const cookie=(r,n)=>{for(const x of(r.headers.get("Cookie")||"").split(";")){const[a,...v]=x.trim().split("=");if(a===n)return decodeURIComponent(v.join("="))}return""};const setc=(n,v,age)=>`${n}=${encodeURIComponent(v)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${age}; Secure`;const limit=(r,k,n,w)=>{const key=k+":"+(r.headers.get("CF-Connecting-IP")||"x"),t=Date.now(),e=R.get(key);if(!e||t-e.t>w){R.set(key,{t,c:1});return 1}e.c++;return e.c<=n};
async function user(r,e){const t=cookie(r,"f_session");if(!t)return null;return e.DB.prepare("SELECT u.id,u.username,u.role,u.status,u.best_score bestScore,u.games FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(await hash(t),Date.now()).first()}
async function auth(r,e,admin=false){const u=await user(r,e);if(!u||u.status!=="active"||(admin&&u.role!=="admin"))return null;return u}
async function api(r,e){const p=new URL(r.url).pathname;
if(p==="/api/config")return j({sitekey:e.TURNSTILE_SITEKEY||null});
if(p==="/api/me")return j({user:await user(r,e)});
if(p==="/api/register"&&r.method==="POST"){if(!limit(r,"a",8,900000))return j({error:"Demasiados intentos"},429);const x=await r.json(),u=String(x.username||"").trim(),pw=String(x.password||"");if(!/^[A-Za-z0-9_]{3,16}$/.test(u)||pw.length<8)return j({error:"Usuario o contraseña inválidos"},400);if(e.TURNSTILE_SECRET&&!await captcha(x.turnstileToken,r,e))return j({error:"CAPTCHA inválido"},400);const salt=hex(b());const ph=await hash(pw+salt+(e.PASSWORD_PEPPER||""));try{const t=Date.now(),role=e.ADMIN_USERNAME&&u.toLowerCase()===e.ADMIN_USERNAME.toLowerCase()?"admin":"user",z=await e.DB.prepare("INSERT INTO users(username,password_hash,salt,role,status,best_score,games,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(u,ph,salt,role,"active",0,0,t).run(),id=z.meta.last_row_id,tok=enc(b());await e.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").bind(await hash(tok),id,t+604800000).run();return j({user:{id,username:u,role,status:"active",bestScore:0,games:0}},201,{"Set-Cookie":setc("f_session",tok,604800)})}catch{return j({error:"Ese usuario ya existe"},409)}}
if(p==="/api/login"&&r.method==="POST"){if(!limit(r,"a",8,900000))return j({error:"Demasiados intentos"},429);const x=await r.json(),u=String(x.username||"").trim(),pw=String(x.password||"");if(e.TURNSTILE_SECRET&&!await captcha(x.turnstileToken,r,e))return j({error:"CAPTCHA inválido"},400);const z=await e.DB.prepare("SELECT * FROM users WHERE username=?").bind(u).first();if(!z||await hash(pw+z.salt+(e.PASSWORD_PEPPER||""))!==z.password_hash)return j({error:"Usuario o contraseña incorrectos"},401);const tok=enc(b());await e.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").bind(await hash(tok),z.id,Date.now()+604800000).run();return j({user:{id:z.id,username:z.username,role:z.role,status:z.status,bestScore:z.best_score,games:z.games}},200,{"Set-Cookie":setc("f_session",tok,604800)})}
if(p==="/api/logout"){const t=cookie(r,"f_session");if(t)await e.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await hash(t)).run();return j({ok:true},200,{"Set-Cookie":setc("f_session","",0)})}
if(p==="/api/ranking"){const z=await e.DB.prepare("SELECT username,best_score score,games FROM users WHERE games>0 ORDER BY best_score DESC,id ASC LIMIT 100").all();return j({ranking:z.results||[]})}
if(p==="/api/game"&&r.method==="POST"){const u=await auth(r,e);if(!u)return j({error:"Inicia sesión"},403);const id=enc(b()),t=Date.now();await e.DB.prepare("INSERT INTO games(id,user_id,idx,score,started_at) VALUES(?,?,?,?,?)").bind(id,u.id,0,0,t).run();return j({gameId:id,question:pub[0],total:pub.length})}
if(p==="/api/answer"&&r.method==="POST"){const u=await auth(r,e);if(!u)return j({error:"Inicia sesión"},403);const x=await r.json(),g=await e.DB.prepare("SELECT * FROM games WHERE id=? AND user_id=?").bind(String(x.gameId),u.id).first();if(!g)return j({error:"Partida inválida"},400);const q=Q[g.idx],ok=Number(x.choice)===q[3],pts=ok?100:0,score=g.score+pts,next=g.idx+1;if(next>=Q.length){await e.DB.batch([e.DB.prepare("UPDATE users SET games=games+1,best_score=MAX(best_score,?),updated_at=? WHERE id=?").bind(score,Date.now(),u.id),e.DB.prepare("DELETE FROM games WHERE id=?").bind(g.id)]);return j({ok,points:pts,score,done:true})}await e.DB.prepare("UPDATE games SET idx=?,score=? WHERE id=?").bind(next,score,g.id).run();return j({ok,points:pts,score,done:false,question:pub[next]})}
if(p==="/api/dev/open"&&r.method==="POST"){const u=await auth(r,e,true);if(!u)return j({error:"No autorizado"},403);const x=await r.json();if(!e.DEV_PANEL_CODE||x.code!==e.DEV_PANEL_CODE)return j({error:"Código incorrecto"},403);const t=enc(b());await e.DB.prepare("INSERT INTO dev_sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").bind(await hash(t),u.id,Date.now()+3600000).run();return j({ok:true},200,{"Set-Cookie":setc("f_dev",t,3600)})}
const dt=cookie(r,"f_dev"),adm=await auth(r,e,true);if(p==="/api/dev/users"&&adm&&dt){const d=await e.DB.prepare("SELECT user_id FROM dev_sessions WHERE token_hash=? AND expires_at>?").bind(await hash(dt),Date.now()).first();if(!d)return j({error:"Sesión de desarrollador expirada"},403);const z=await e.DB.prepare("SELECT id,username,role,status,best_score bestScore,games FROM users ORDER BY id DESC").all();return j({users:z.results||[]})}
const m=p.match(/^\/api\/dev\/(\d+)\/score$/);if(m&&r.method==="POST"&&adm&&dt){const d=await e.DB.prepare("SELECT user_id FROM dev_sessions WHERE token_hash=? AND expires_at>?").bind(await hash(dt),Date.now()).first();if(!d)return j({error:"No autorizado"},403);const x=await r.json(),delta=Number(x.delta);if(!Number.isSafeInteger(delta)||Math.abs(delta)>1000000000)return j({error:"Valor inválido"},400);await e.DB.prepare("UPDATE users SET best_score=MAX(0,best_score+?) WHERE id=?").bind(delta,Number(m[1])).run();return j({ok:true})}
return null}
async function captcha(token,r,e){if(!token)return false;const f=new FormData();f.append("secret",e.TURNSTILE_SECRET);f.append("response",token);const z=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:f});return z.ok&&(await z.json()).success}
export default{async fetch(r,e){try{if(new URL(r.url).pathname.startsWith("/api/"))return (await api(r,e))||j({error:"No encontrado"},404);return e.ASSETS.fetch(r)}catch(x){return j({error:"Error interno"},500)}}};