name = "futboliq"
main = "worker.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "futboliq-db"
database_id = "9e6ceba3-be65-4fe7-ac06-a6b20009a209"
migrations_dir = "migrations"
